apcu and session destruction
bnw/firefly-iii-fints-importer pull request #119
Opened 2023-10-29 09:56 UTC by TyrionWarMage

- Cleanup session on proper exit
- Added a warning about local file session
- If APCu is enabled, password is memory stored.
- Closes #118 

The session cleanup should also be added to the error handler, but i was not able to get this running.

2023-11-06 17:53 UTC, TyrionWarMage commented
After investigating some more, it seems the "preferred" way to resolve this issue woud be using a shared memory session handler.

- mm - requires recompiling php with custom config
- memcache/memcached - requires setting a dedicated memcache server

The solutions would be cleaner, but are much more involved and probably a bit of overkill, at least in my opinion.

2023-11-22 21:09 UTC, TyrionWarMage commented
In case you are not satisfied with this solution, alternatives i could provide are:

- Createing an apcu-based session replacement. Much cleaner code, but not advised as this would not support proper locking: https://stackoverflow.com/questions/1724587/how-to-store-php-sessions-in-apc-cache. However, probably not an issue with this tool.
- Completely remove apcu and only check for memcached setup with a warning. However, installing apcu is simpler than memcached and therefore more friendly users.

2024-08-09 09:26 UTC, bnw commented
Hi @TyrionWarMage,
thanks a lot for your work. Sorry again for the late reply.
Unfortunately, I know very little about the safety implications of this change. If we write the pin into some globaly accessible apcu, don't we make it available to every php script on the system? 😅

2024-08-09 19:03 UTC, TyrionWarMage commented
According to https://stackoverflow.com/questions/34533695/is-the-new-apcu-apc-user-cache-shared-between-processes, it will be shared between all Apache/Nginx sessions, but not CLI. Surely not optimal, but probably beats a plain text file, readable by every script/process running with the same user or group. Furthermore, the cache is cleared once the import is done and it is required to manually enable APCu.

I'm also no security expert but i usually try to secure my file system, but think if an intruder is in your memory, everything is too late anyhow...

Of course,I'm for merging, but it is your call ... Just let me know.

2024-08-10 10:19 UTC, bnw commented
Ok, I guess you are right and this improves the situation. I'm willing to merge this, but have two requests:
1. Could you consolidate all the apuc code into one class? Maybe some PasswordStorage class or similar?
2. Could you double-check that apcu is working in the docker container? This will ensure that the pin is stored in memory at least for this common use-case. Maybe you could add a simple unit test for this? The [github action will run the test inside the built docker container](https://github.com/bnw/firefly-iii-fints-importer/blob/8c8063ca71943814a7a92c45e40cee6250ffe02f/.github/workflows/publish-docker-image.yml#L42).

Thanks again for your work and your input 😊 🙏

2024-08-12 21:18 UTC, TyrionWarMage commented
> Ok, I guess you are right and this improves the situation. I'm willing to merge this, but have two requests:
> 
>     1. Could you consolidate all the apuc code into one class? Maybe some PasswordStorage class or similar?
> 
>     2. Could you double-check that apcu is working in the docker container? This will ensure that the pin is stored in memory at least for this common use-case. Maybe you could add a simple unit test for this? The [github action will run the test inside the built docker container](https://github.com/bnw/firefly-iii-fints-importer/blob/8c8063ca71943814a7a92c45e40cee6250ffe02f/.github/workflows/publish-docker-image.yml#L42).
> 
> 
> Thanks again for your work and your input 😊 🙏

Done. I'm reusing the global session object to not require instantiating the new class. Alternatively, i could make the session an argument, but i preferred this way because session is only used in the not-apcu path

2024-08-13 19:19 UTC, bnw requested changes
It's looking good already, thanks! I only have a few small requests.

2024-08-13 19:19 UTC, bnw commented on app/public/html/setup.twig
> +    <p>{{ warning }}</p>
Probably, we do not want the extra `<p>` if there is no warning.

2024-08-13 19:19 UTC, bnw commented on app/RunImportBatched.php
> +    return $result;
What's the reason for this change? :)

2024-08-13 19:19 UTC, bnw commented on app/FinTsFactory.php
> +        foreach(['bank_url','bank_code','bank_username','bank_2fa'] as $required_session_value){
Instead of simply removing the "password is set" sanity check here, could you replace it with an equivalent check using the new system?

2024-08-13 19:19 UTC, bnw commented on app/PasswordStorage.php
> +            apcu_store('firefly_fints_bank_password', $pwd);
Could you add asserts here to the `apcu_store` and `apcu_fetch` calls that give meaningfull error messages, when things are not working. I think you would have to check the "success" flag of apcu_fetch and the return value of apcu_store?

2024-08-14 15:36 UTC, TyrionWarMage commented
All Done

2024-08-14 22:12 UTC, bnw commented
Thanks you so much ❤️

2024-08-14 22:13 UTC, merged