Automate choose account
bnw/firefly-iii-fints-importer pull request #63
Opened 2022-03-07 00:01 UTC by Bur0k

Based on #62 (Merge it before)

This solves fully or partially the following issues:
- #25 
- #27 (I am not sure about this)
- #40

Importing will always use the default time period.

2022-04-12 09:28 UTC, Bur0k commented
Are there any concerns regarding this PR or was there not enough time to review/test it?

2022-04-17 10:19 UTC, bnw commented
Hi, 
sorry for the delay. 
Could you rebase/cherry-pick the MR to the changes introduced in #62 so that "Files changed" only shows what actually changes in this MR? 
Thanks :)

2022-04-22 17:05 UTC, Bur0k commented
I knew that i forgot something - Thanks for the heads up about the rebase :)

Added another commit so it does not log an error when the automation configs for these steps are missing. (Forgot that in my last PR)

2022-04-24 11:48 UTC, bnw requested changes

2022-04-24 11:48 UTC, bnw commented on app/public/html/choose-account.twig
> +        </script>
Hm, this is a bit awkward:  
This leaves the user with 2 seconds to change the dates.  

How about adding the from and to date (e.g. in the form 'now - 1 month') to the config too? Then, we auto-skip this form iff all four values (bank_account, firefly_account, date_from, date_to) are provided.

2022-04-24 20:42 UTC, Bur0k commented
I moved the configs for this "Choose Automation" step into its own JSON Object - It became too cluttered for me.

Regarding your `from_date` and `to_date` comment: Is this a good way to implement it? I just passed it right into the `DateTime` constructor? This should not be a security issue, right?

2022-06-19 20:50 UTC, bnw approved these changes

2022-06-19 21:03 UTC, merged

2022-06-19 21:03 UTC, bnw commented
Thanks a lot for your work and sorry for the delay :)